=== nathonfowlie/python.weathersimulator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Locations",
  "type": "array",
  "minItems": 0,
  "uniqueItems": true,
  "items": {
    "title": "Location",
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "latitude": {
        "type": "number"
      },
      "longitude": {
        "type": "number"
      },
      "elevation": {
        "type": "integer"
      },
      "temps": {
        "type": "object",
        "properties": {
          "min": {
            "type": "array",
            "minItems": 12,
            "maxItems": 12,
            "items": {
              "type": "number"
            }
          },
          "max": {
            "type": "array",
            "minItems": 12,
            "maxItems": 12,
            "items": {
              "type": "number"
            }
          }
        },
        "required": [
          "min",
          "max"
        ]
      }
    },
    "required": [
      "name",
      "latitude",
      "longitude",
      "elevation",
      "temps"
    ]
  }
}

=== nathonfowlie/python.weathersimulator/data/locations.json
[
    {
        "name": "Sydney",
        "latitude": -33.8688197,
        "longitude": 151.2092955,
        "elevation": 40,
        "temps": {
            "min": [ 10.6, 9.6, 9.3, 7.0, 4.4, 2.1, 2.2, 2.7, 4.9, 5.7, 7.7, 9.1 ],
            "max": [ 45.8, 42.1, 39.8, 34.2, 30.0, 26.9, 25.9, 31.3, 34.6, 38.2, 41.8, 42.2 ]
        }
    },
    {
        "name": "Melbourne",
        "latitude": 28.0836269,
        "longitude": -80.6081089,
        "elevation": 25,
        "temps": {
            "min": [ 5.5, 4.5, 2.8, 1.5, -1.1, -2.2, -2.8, -2.1, -0.5, 0.1, 2.5, 4.4 ],
            "max": [ 45.6, 46.4, 41.7, 34.9, 28.7, 22.4, 23.1, 26.5, 31.4, 36.9, 40.9, 43.7 ]
        }
    },
    {
        "name": "Adelaide",
        "latitude": -34.92577,
        "longitude": 138.599732,
        "elevation": 59,
        "temps": {
            "min": [ 9.2, 9.5, 7.2, 4.3, 1.5, -0.4, 0.4, 0.9, 2.6, 4.7, 5.3, 7.9 ],
            "max": [ 45.7, 44.7, 41.9, 36.9, 31.1, 25.4, 23.1, 30.4, 34.3, 39.0, 43.0, 43.4 ]
        }
    },
    {
        "name": "Canberra",
        "latitude": -35.2834600,
        "longitude": 149.1280700,
        "elevation": 571,
        "temps": {
            "min": [ 1.6, 3.0, -1.1, -3.7, -7.5, -8.5, -10.0, -8.5, -6.8, -3.4, -1.8, 0.3 ],
            "max": [ 42.0, 42.2, 37.5, 32.6, 24.5, 20.1, 19.7, 24.0, 28.6, 32.7, 39.9, 39.2 ]
        }
    },
    {
        "name": "Perth",
        "latitude":  -31.9522400,
        "longitude": 115.8614000,
        "elevation": 34,
        "temps": {
            "min": [ 16.6, 16.7, 15.1, 11.7, 8.8, 5.8, 4.4, 5.6, 7.6, 9.7, 12.4, 13.9 ],
            "max": [ 33.5, 34.6, 31.9, 28.5, 24.4, 21.0, 19.5, 21.6, 22.5, 26.8, 29.6, 31.5 ]
        }
    },
    {
        "name": "Brisbane",
        "latitude": -27.4679400,
        "longitude": 153.0280900,
        "elevation": 27,
        "temps": {
            "min": [ 20.0, 19.8, 18.1, 15.6, 12.2, 10.3, 8.0, 8.9, 12.6, 14.7, 17.2, 18.7 ],
            "max": [ 31.5, 32.5, 30.8, 28.8, 27.0, 23.3, 23.0, 25.5, 27.6, 28.8, 30.2, 32.1 ]
        }
    },
    {
        "name": "Hobart",
        "latitude":  -42.8793600,
        "longitude": 147.3294100,
        "elevation": 19,
        "temps": {
            "min": [ 10.1, 9.5, 8.2, 6.6, 4.7, 2.9, 2.2, 2.9, 4.1, 5.8, 7.4, 8.7 ],
            "max": [ 25.0, 25.2, 22.9, 20.4, 17.3, 14.1, 13.9, 15.7, 17.9, 19.7, 21.5, 24.0 ]
        }
    },
    {
        "name": "Alice Springs",
        "latitude": -23.6974800,
        "longitude": 133.8836200,
        "elevation": 583,
        "temps": {
            "min": [ 16.8, 16.2, 14.2, 8.3, 1.4, -0.1, -1.0, 1.7, 7.0, 10.8, 14.3, 17.0 ],
            "max": [ 40.0, 39.1, 36.9, 33.5, 27.2, 23.6, 22.9, 28.1, 33.3, 35.4, 37.1, 38.4 ]
        }
    },
    {
        "name": "Darwin",
        "latitude": -12.4611300,
        "longitude": 130.8418500,
        "elevation": 31,
        "temps": {
            "min": [ 20.2, 17.2, 19.2, 16.0, 13.8, 12.1, 10.4, 13.0, 14.3, 19.0, 19.3, 19.8 ],
            "max": [ 36.1, 36.0, 36.0, 36.7, 36.0, 34.6, 34.8, 37.0, 37.7, 38.9, 37.3, 37.0 ]
        }
    },
    {
        "name": "Gold Coast",
        "latitude":  -28.0002900,
        "longitude": 153.4308800,
        "elevation": 12,
        "temps": {
            "min": [ 17.2, 17.2, 13.4, 8.9, 6.6, 3.8, 2.5, 4.2, 7.9, 9.4, 8.2, 14.7 ],
            "max": [ 38.5, 40.5, 36.3, 33.3, 29.4, 27.1, 28.9, 32.4, 33.0, 36.8, 35.5, 39.4 ]
        }
    },
    {
        "name": "Cairns",
        "latitude": -16.9230400,
        "longitude": 145.7662500,
        "elevation": 7,
        "temps": {
            "min": [ 22.5, 22.5, 21.7, 19.6, 16.8, 14.5, 14.2, 15.0, 16.0, 17.7, 20.6, 21.6 ],
            "max": [ 33.6, 33.5, 32.5, 31.2, 29.3, 27.8, 27.5, 28.5, 30.0, 30.9, 32.2, 33.2 ]
        }
    },
    {
        "name": "Kalgoorlie",
        "latitude": -30.7461400,
        "longitude": 121.4742000,
        "elevation": 387,
        "temps": {
            "min": [ 16.3, 14.8, 13.8, 9.3, 5.7, 4.1, 1.7, 2.2, 5.7, 8.1, 12.0, 14.2 ],
            "max": [ 36.6, 37.0, 33.1, 29.5, 24.4, 20.0, 20.2, 23.9, 25.5, 31.0, 32.7, 36.5 ]
        }
    },
    {
        "name": "Broome",
        "latitude": -17.9553800,
        "longitude": 122.2392200,
        "elevation": 12,
        "temps": {
            "min": [ 19.0, 15.2, 16.0, 12.6, 7.7, 5.2, 3.3, 4.8, 8.9, 13.3, 16.7, 17.4 ],
            "max": [ 44.1, 42.7, 42.2, 41.0, 38.7, 36.2, 36.0, 37.8, 41.3, 42.8, 44.3, 44.8 ]
        }
    },
    {
        "name": "Mildura",
        "latitude": -34.1855100,
        "longitude": 142.1625100,
        "elevation": 56,
        "temps": {
            "min": [ 7.6, 5.2, 3.8, 0.6, -2.1, -3.7, -4.0, -3.1, -1.1, 1.1, 3.3, 5.3 ],
            "max": [ 46.9, 46.7, 42.1, 37.8, 29.6, 25.4, 26.8, 29.9, 37.4, 40.2, 45.5, 45.1 ]
        }
    },
    {
        "name": "Geelong",
        "latitude": -38.1471100,
        "longitude": 144.3606900,
        "elevation": 23,
        "temps": {
            "min": [ 4.5, 6.8, 2.9, 0.6, -0.7, -2.9, -2.5, -4.4, -1.0, 0.1, 2.9, 4.8 ],
            "max": [ 46.3, 47.9, 42.0, 36.1, 28.0, 23.6, 22.5, 25.9, 31.3, 37.8, 39.5, 45.0 ]
        }
    },
    {
        "name": "Kadina",
        "latitude": -33.9649500,
        "longitude": 137.7163400,
        "elevation": 46,
        "temps": {
            "min": [ 7.4, 7.8, 4.3, 1.5, -0.7, -2.5, -3.0, -3.6, -1.0, 1.7, 3.8, 6.2 ],
            "max": [ 44.5, 46.0, 39.7, 36.0, 28.2, 24.7, 23.4, 28.4, 34.7, 39.0, 43.8, 42.2 ]
        }
    },
    {
        "name": "Whyalla",
        "latitude": -33.0326800,
        "longitude": 137.5648300,
        "elevation": 20,
        "temps": {
            "min": [ 5.9, 8.6, 5.5, 2.2, -0.4, -3.2, -3.2, -2.0, 0.4, 0.3, 3.9, 4.7 ],
            "max": [ 47.2, 48.0, 44.1, 40.4, 32.9, 26.3, 27.0, 32.0, 38.0, 42.1, 45.5, 45.8 ]
        }
    },
    {
        "name": "Townsville",
        "latitude": -19.2663900,
        "longitude": 146.8056900,
        "elevation": 15,
        "temps": {
            "min": [ 18.7, 17.9, 16.7, 10.9, 6.2, 4.4, 3.5, 1.1, 7.7, 8.2, 14.1, 17.9 ],
            "max": [ 44.3, 42.7, 37.6, 35.8, 32.2, 32.2, 31.6, 33.3, 36.5, 37.1, 41.0, 42.1 ]
        }
    },
    {
        "name": "Dubbo",
        "latitude": -32.2429500,
        "longitude": 148.6048400,
        "elevation": 264,
        "temps": {
            "min": [ 5.8, 6.3, 3.4, -2.2, -4.0, -4.9, -5.4, -4.7, -3.2, -0.4, 2.0, 4.5 ],
            "max": [ 45.0, 46.1, 39.5, 33.9, 28.6, 23.0, 29.2, 28.3, 33.7, 38.1, 44.3, 42.1 ]
        }
    },
    {
        "name": "Orange",
        "latitude": -33.2839700,
        "longitude": 149.1001800,
        "elevation": 868,
        "temps": {
            "min": [ 1.1, 1.3, -0.1, -4.6, -6.6, -8.3, -7.7, -6.2, -5.4, -3.0, -1.7, 0.0 ],
            "max": [ 38.1, 40.1, 32.9, 28.1, 21.5, 18.6, 15.8, 19.5, 24.3, 28.7, 37.9, 34.7 ]
        }
    }
]
